import './style.css'

const app = document.querySelector<HTMLDivElement>('#app')!

app.innerHTML = `
  <header class="site-header">
    <a class="wordmark" href="#top" aria-label="Juveria Khatoon home">JK<span>.</span></a>
    <nav class="site-nav" aria-label="Primary navigation"><a href="#experience">Experience</a><a href="#mentorship">Mentorship</a><a href="#contact">Contact</a></nav>
    <a class="header-link" href="/Juveria_Khatoon_Resume.pdf" download>Resume <span aria-hidden="true">↗</span></a>
  </header>
  <main id="top">
    <section class="hero section-shell" aria-labelledby="hero-title">
      <div class="hero-copy reveal"><p class="eyebrow"><span class="status-dot"></span> Open to meaningful opportunities</p><h1 id="hero-title">Building useful systems with <em>clarity</em> and care.</h1><p class="hero-intro">I’m Juveria, a Full Stack .NET Developer who turns complex enterprise problems into resilient products, thoughtful interfaces, and better ways of working.</p><div class="hero-actions"><a class="button button-primary" href="#contact">Let’s talk <span aria-hidden="true">↗</span></a><a class="text-link" href="#mentorship">Explore mentorship <span aria-hidden="true">↓</span></a></div><div class="hero-meta"><span>Based in Hyderabad, India</span><span>6+ years in product engineering</span></div></div>
      <div class="hero-portrait reveal"><div class="portrait-frame"><img src="/myPic.jpg" alt="Portrait of Juveria Khatoon" /></div><div class="portrait-note"><span>Currently showing up as</span><strong>Engineer · Mentor · Volunteer</strong></div><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div></div>
    </section>
    <section class="signal-strip" aria-label="Personal qualities"><div><strong>Creative</strong><span>turning ideas into useful experiences</span></div><div><strong>Intuitive</strong><span>making complexity feel clear</span></div><div><strong>Articulate</strong><span>communicating with clarity and care</span></div><div><strong>Curious</strong><span>always asking what’s next</span></div></section>
    <section class="section-shell about-section" id="about" aria-labelledby="about-title"><div class="section-label">01 / About</div><div class="about-grid"><h2 id="about-title">A pragmatic engineer with a frontend heart.</h2><div class="about-copy"><p>I work across the stack, from secure APIs and data models to the final interaction a person feels in the browser. My sweet spot is the space between strong technical foundations and interfaces that make sense.</p><p>At Deloitte USI, I’ve helped modernize monolithic systems, ship scalable Angular applications, and make teams more confident through testing, clear patterns, and steady collaboration.</p></div></div></section>
    <section class="dark-section" id="experience" aria-labelledby="experience-title"><div class="section-shell"><div class="section-label light-label">02 / Experience</div><div class="section-heading-row"><h2 id="experience-title">Growing with the work.</h2><span class="heading-aside">Deloitte USI · 2020—Present</span></div><div class="timeline"><article class="timeline-item"><div class="timeline-date">JUN 2023 — NOW</div><div><h3>Software Engineer 2</h3><p class="timeline-company">Deloitte USI · Hyderabad, India</p><p>Architecting enterprise web applications with C#, ASP.NET Core, Angular, and Azure. I work on system modernization, performance, CI/CD, and the small details that make a platform dependable.</p><div class="tag-list"><span>Architecture</span><span>Azure microservices</span><span>Angular 17</span><span>Performance</span></div></div></article><article class="timeline-item"><div class="timeline-date">OCT 2020 — JUN 2023</div><div><h3>Software Engineer 1</h3><p class="timeline-company">Deloitte USI · Hyderabad, India</p><p>Built RESTful APIs and reusable Angular experiences, strengthened application security with JWT and Azure Key Vault, and helped teams ship with confidence through automated testing.</p><div class="tag-list"><span>ASP.NET Core</span><span>RxJS</span><span>xUnit</span><span>Agile delivery</span></div></div></article></div></div></section>
    <section class="section-shell skills-section" id="skills" aria-labelledby="skills-title"><div class="section-label">03 / Toolkit</div><div class="section-heading-row"><h2 id="skills-title">The tools behind the thinking.</h2><p class="heading-aside">A stack is useful when it serves the people using it.</p></div><div class="skills-grid"><div class="skill-group"><span class="skill-number">01</span><h3>Frontend</h3><p>Angular 16/17/18<br>TypeScript · RxJS · NgRx<br>HTML · CSS · Responsive UI</p></div><div class="skill-group"><span class="skill-number">02</span><h3>Backend</h3><p>C# · .NET Core<br>ASP.NET Core Web API<br>REST · Microservices · EF Core</p></div><div class="skill-group"><span class="skill-number">03</span><h3>Cloud & data</h3><p>Microsoft Azure · Functions<br>App Services · Azure DevOps<br>SQL Server · CI/CD</p></div><div class="skill-group"><span class="skill-number">04</span><h3>Quality & craft</h3><p>Jasmine · Karma<br>Agentic AI · RAG<br>Prompt Engineering · GitHub Copilot</p></div></div></section>
    <section class="mentorship-section" id="mentorship" aria-labelledby="mentorship-title"><div class="section-shell mentorship-grid"><div><div class="section-label">04 / Mentorship</div><h2 id="mentorship-title">You don’t have to figure out the next step alone.</h2></div><div class="mentorship-copy"><p>I support students, freshers, and junior developers as they prepare for placements, crack technical interviews, and take their first steps into tech.</p><a class="button button-dark" href="#contact">Start a conversation <span aria-hidden="true">↗</span></a></div></div></section>
    <section class="section-shell lower-grid" aria-label="Additional information"><div class="lower-panel"><div class="section-label">05 / Keep learning</div><h2>Notes are coming.</h2><p>A growing collection of practical thoughts on frontend architecture, engineering growth, and building with AI thoughtfully.</p><span class="coming-soon">Writing / Resources · Soon</span></div><div class="lower-panel"><div class="section-label">06 / Beyond the code</div><h2>Make an impact that travels.</h2><p>Led volunteer teams, coordinated digital literacy programs reaching 500+ beneficiaries, and served as Chief Coordinator for the Computer Society of India at my University</p><div class="credentials"><span>AZ-900</span><span>GH-300</span><span>SAFe 5</span></div></div></section>
    <section class="contact-section" id="contact" aria-labelledby="contact-title"><div class="section-shell contact-grid"><div><div class="section-label light-label">07 / Contact</div><h2 id="contact-title">Let’s make something <em>meaningful.</em></h2><p>For opportunities, collaborations, or a mentorship question, I’d love to hear what you’re working on.</p><div class="contact-links"><a href="mailto:juveria.khatoon6@gmail.com">juveria.khatoon6@gmail.com</a><a href="https://www.linkedin.com/in/juveriak" target="_blank" rel="noreferrer">LinkedIn <span aria-hidden="true">↗</span></a></div></div><form name="contact" method="POST" action="/success.html" data-netlify="true" netlify-honeypot="bot-field" class="contact-form"><input type="hidden" name="form-name" value="contact"><p class="hidden-field"><label>Don’t fill this out: <input name="bot-field"></label></p><label for="name">Your name</label><input id="name" name="name" type="text" required placeholder="Jane Smith"><label for="email">Email address</label><input id="email" name="email" type="email" required placeholder="jane@example.com"><label for="topic">What can I help with?</label><select id="topic" name="topic" required><option value="" disabled selected>Choose a topic</option><option>Professional opportunity</option><option>Mentorship</option><option>Collaboration</option><option>Something else</option></select><button class="button button-accent" type="submit">Send message <span aria-hidden="true">↗</span></button></form></div></section>
  </main>
  <footer class="site-footer section-shell"><span>© 2026 Juveria Khatoon</span><span>Built with intention · Hyderabad, India</span><a href="#top">Back to top ↑</a></footer>`
const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) entry.target.classList.add('is-visible') }), { threshold: 0.12 })
document.querySelectorAll('.reveal, .timeline-item, .skill-group, .lower-panel').forEach((element) => observer.observe(element))
